all:
  hosts:
    debian-local:
      ansible_host: 127.0.0.1
      ansible_connection: local
    debian_vm-01:
      ansible_host: 192.168.140.XX
      ansible_port: 22
      ansible_user: debian
      ansible_ssh_extra_args: "-o IdentitiesOnly=yes"
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_private_key_file: "path/to/your-key-file.pem"
    debian_vm-02:
      ansible_host: 192.168.140.XX
      ansible_port: 22
      ansible_user: debian
      ansible_ssh_extra_args: "-o IdentitiesOnly=yes"
      ansible_ssh_private_key_file: "path/to/your-key-file.pem"
  children:
    webservers:
      hosts:
        debian_vm-01:
        debian_vm-02: