all:
  hosts:
    debian_VM02:
      ansible_host: 192.168.140.XX
      ansible_port: 22
      ansible_user: debian
      ansible_ssh_extra_args: "-o ForwardAgent=yes -o IdentitiesOnly=yes"
      ansible_ssh_private_key_file: ~/.ssh/my-private-key.pem