---
- name: Updating APT index
  hosts: all
  pre_tasks:
    - name: Update repositories cache
      ansible.builtin.apt:
        update_cache: yes

- name: Installing Nginx server
  hosts: web
  tasks:
    - name: Latest Nginx version installed
      ansible.builtin.apt:
        name: nginx
        state: latest
    - name: Ensure Nginx is enabled and running
      ansible.builtin.service:
        name: nginx
        enabled: true
        state: started
    - name: Copy Nginx configuration file
      copy:
        src: nginx/status.conf
        dest: /etc/nginx/conf.d/status.conf
      notify:
          - restart_nginx
  handlers:
    - name: restart_nginx
      service:
        name: nginx
        state: restarted

- name: Installing MariaDB server
  hosts: db
  tasks:
    - name: Latest MariaDB version installed
      ansible.builtin.apt:
        name: mariadb-server
        state: latest
    - name: Ensure MariaDB is enabled and running
      ansible.builtin.service:
        name: mariadb
        enabled: true
        state: started

- name: Installing Git and PHP server
  hosts: app
  tasks:
    - name: Installing packages
      ansible.builtin.apt:
        pkg:
          - php-fpm
          - git
    - name: Ensure PHP is enabled and running
      ansible.builtin.service:
        name: php7.4-fpm
        enabled: true
        state: started
    - name: Copy PHP configuration file
      ansible.builtin.copy:
        src: php/php.ini
        dest: /etc/php/7.4/fpm/php.ini
      notify:
          - restart_php-fpm
  handlers:
    - name: restart_php-fpm
      ansible.builtin.service:
        name: php7.4-fpm
        state: restarted